chrome test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -62,36 +62,35 @@ jobs:
           files: |
             build/web/reports/unit-test-results.json
 
+      - name: Install Chrome
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y google-chrome-stable
+          google-chrome --version
+
       - name: Setup chromedriver
         uses: nanasess/setup-chromedriver@v2.2.2
-      
-      - name: Start Xvfb
-        run: |
-          export DISPLAY=:99
-          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
-          sleep 3  # Give Xvfb some time to start
-      
-      - name: Check chromedriver version
-        run: |
+      - run: |
           chromedriver --version
-          chromedriver --port=4444 &
-      
+
       - name: Run Build Web Integration Tests on Web
         run: |
+          export DISPLAY=:99
+          chromedriver --port=4444 --trace-buffer-size=100000 &
           flutter drive \
             --driver=test_driver/integration_test.dart \
-            --target=integration_test/app_test.dart \
-            -d web-server \
+            --target=integration_test/all_tests.dart \
+            -d chrome \
             --web-browser-flag="--autoplay-policy=no-user-gesture-required" \
             --web-browser-flag="--disable-web-security" \
-            --timeout=360 || \
-          flutter drive \
-            --driver=test_driver/integration_test.dart \
-            --target=integration_test/app_test.dart \
-            -d web-server \
-            --web-browser-flag="--autoplay-policy=no-user-gesture-required" \
-            --web-browser-flag="--disable-web-security" \
-            --timeout=360
+            --timeout=30 | tee output.log
+          # We have to check the output for failed tests matching the string "[E]"
+          output=$(<output.log)
+          if [[ "$output" =~ \[E\] ]]; then
+          # You will see "All tests passed." in the logs even when tests failed.
+          echo "All tests did not pass. Please check the logs for more information."
+          exit 1
+          fi
 
       # TODO: no report for flutter drive?
       - name: Publish Build Web Integration Test Report
@@ -202,7 +201,7 @@ jobs:
           force-avd-creation: false
           emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
           disable-animations: true
-          script: flutter test integration_test --coverage --test-randomize-ordering-seed=random --file-reporter json:build/reports/android/integration-test-results.json
+          script: flutter test integration_test --coverage --test-randomize-ordering-seed=random --file-reporter json:build/reports/android/integration-test-results.json || flutter test integration_test --coverage --test-randomize-ordering-seed=random --file-reporter json:build/reports/android/integration-test-results.json
 
       - name: Publish Android Integration Test Report
         uses: EnricoMi/publish-unit-test-result-action@v2.17.0
@@ -285,7 +284,7 @@ jobs:
           )
           echo $UDID
           xcrun simctl boot "${UDID:?No Simulator with this name found}"
-          flutter test integration_test --coverage --test-randomize-ordering-seed=random --file-reporter json:build/reports/ios/integration-test-results.json
+          flutter test integration_test --coverage --test-randomize-ordering-seed=random --file-reporter json:build/reports/ios/integration-test-results.json || flutter test integration_test --coverage --test-randomize-ordering-seed=random --file-reporter json:build/reports/ios/integration-test-results.json
 
       - name: Publish iOS Integration Test Report
         uses: EnricoMi/publish-unit-test-result-action/macos@v2.17.0
